<?php

namespace Database\Seeders;

use App\Models\Painting;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PaintingSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            // ── Data lama (hanya untuk sewa, sale_price null) ─────────
            [
                'title'        => 'Senja di Kamar Biru',
                'artist'       => 'Aulia Santoso',
                'category'     => 'Lukisan kontemporer',
                'description'  => 'Lukisan suasana senja yang tenang dengan palet biru tua dan oranye lembut.',
                'year_created' => '2021',
                'media'        => 'Cat akrilik di kanvas',
                'dimensions'   => '90 × 70 cm',
                'daily_rate'   => 125000,
                'available'    => true,
                'image_path'   => 'senja-di-kamar-biru.svg',
                'gallery_paths'=> ['potret-cerita.svg', 'gelombang-biru.svg'],
                'extra_info'   => 'Karya ini pernah dipamerkan pada pameran keliling museum tahun 2023.',
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Potret Cerita',
                'artist'       => 'Bima Rahayu',
                'category'     => 'Potret',
                'description'  => 'Potret dengan ekspresi mendalam dan garis-garis halus pada latar emas.',
                'year_created' => '2019',
                'media'        => 'Cat minyak di kanvas',
                'dimensions'   => '80 × 60 cm',
                'daily_rate'   => 155000,
                'available'    => true,
                'image_path'   => 'potret-cerita.svg',
                'gallery_paths'=> null,
                'extra_info'   => null,
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Gelombang Biru',
                'artist'       => 'Dewi Kurnia',
                'category'     => 'Abstrak',
                'description'  => 'Karya abstrak yang menangkap gerak gelombang air dengan warna biru cerah.',
                'year_created' => '2020',
                'media'        => 'Akrilik & pasir tekstur',
                'dimensions'   => '100 × 100 cm',
                'daily_rate'   => 145000,
                'available'    => true,
                'image_path'   => 'gelombang-biru.svg',
                'gallery_paths'=> null,
                'extra_info'   => null,
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Simfoni Urban',
                'artist'       => 'Intan Wulandari',
                'category'     => 'Urban',
                'description'  => 'Komposisi citra kota modern dengan harmoni warna biru dan aksen cahaya.',
                'year_created' => '2022',
                'media'        => 'Spray & akrilik di kanvas',
                'dimensions'   => '120 × 80 cm',
                'daily_rate'   => 135000,
                'available'    => true,
                'image_path'   => 'symphony-urban.svg',
                'gallery_paths'=> null,
                'extra_info'   => null,
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Bayangan Angin',
                'artist'       => 'Rafi Pradana',
                'category'     => 'Abstrak',
                'description'  => 'Visual abstrak yang menangkap gerak angin dan bayangan melalui sapuan seni halus.',
                'year_created' => '2018',
                'media'        => 'Cat minyak di kanvas',
                'dimensions'   => '85 × 65 cm',
                'daily_rate'   => 165000,
                'available'    => true,
                'image_path'   => 'bayangan-angin.svg',
                'gallery_paths'=> null,
                'extra_info'   => null,
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Kilau Pagi',
                'artist'       => 'Fajar Arief',
                'category'     => 'Lukisan kontemporer',
                'description'  => 'Warna hangat dan sapuan dinamis menggambarkan suasana pagi yang penuh harapan.',
                'year_created' => '2023',
                'media'        => 'Akrilik di kanvas',
                'dimensions'   => '70 × 50 cm',
                'daily_rate'   => 145000,
                'available'    => true,
                'image_path'   => 'kilau-pagi.svg',
                'gallery_paths'=> null,
                'extra_info'   => null,
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Rona Malam',
                'artist'       => 'Siska Anindita',
                'category'     => 'Urban',
                'description'  => 'Nuansa malam dengan lampu-lampu kota yang berpendar lembut dalam karya elegan ini.',
                'year_created' => '2017',
                'media'        => 'Cat minyak di kanvas',
                'dimensions'   => '110 × 75 cm',
                'daily_rate'   => 150000,
                'available'    => false,
                'image_path'   => 'rona-malam.svg',
                'gallery_paths'=> null,
                'extra_info'   => 'Saat ini sedang dipinjamkan untuk pameran mitra.',
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Jendela Masa Lalu',
                'artist'       => 'Arman Prabowo',
                'category'     => 'Potret',
                'description'  => 'Sebuah potret nostalgia dengan permainan cahaya yang halus dan dramatis.',
                'year_created' => '2016',
                'media'        => 'Cat minyak di linen',
                'dimensions'   => '95 × 70 cm',
                'daily_rate'   => 170000,
                'available'    => true,
                'image_path'   => 'jendela-masa-lalu.svg',
                'gallery_paths'=> null,
                'extra_info'   => null,
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Ritme Kota',
                'artist'       => 'Nisa Amelia',
                'category'     => 'Urban',
                'description'  => 'Kanvas urban yang penuh garis, warna, dan energi dinamika perkotaan.',
                'year_created' => '2024',
                'media'        => 'Mixed media',
                'dimensions'   => '130 × 90 cm',
                'daily_rate'   => 155000,
                'available'    => true,
                'image_path'   => 'ritme-kota.svg',
                'gallery_paths'=> null,
                'extra_info'   => null,
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Bayang Laut',
                'artist'       => 'Yoga Santoso',
                'category'     => 'Pemandangan',
                'description'  => 'Pemandangan laut abstrak yang menenangkan dengan gelombang warna biru dan putih.',
                'year_created' => '2015',
                'media'        => 'Akrilik di kanvas',
                'dimensions'   => '100 × 60 cm',
                'daily_rate'   => 140000,
                'available'    => true,
                'image_path'   => 'bayang-laut.svg',
                'gallery_paths'=> null,
                'extra_info'   => null,
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Melodi Hutan',
                'artist'       => 'Novi Inggriani',
                'category'     => 'Pemandangan',
                'description'  => 'Kombinasi warna alam yang harmonis, menyerupai alunan melodi di tengah hutan.',
                'year_created' => '2020',
                'media'        => 'Cat minyak di kanvas',
                'dimensions'   => '115 × 80 cm',
                'daily_rate'   => 160000,
                'available'    => false,
                'image_path'   => 'melodi-hutan.svg',
                'gallery_paths'=> null,
                'extra_info'   => null,
                'sale_price'   => null,
                'for_sale'     => false,
            ],
            [
                'title'        => 'Aksara Senja',
                'artist'       => 'Galih Nugroho',
                'category'     => 'Lukisan kontemporer',
                'description'  => 'Siluet dan gradasi senja memberikan sentuhan romantis pada karya ini.',
                'year_created' => '2022',
                'media'        => 'Akrilik di kanvas',
                'dimensions'   => '75 × 55 cm',
                'daily_rate'   => 150000,
                'available'    => true,
                'image_path'   => 'aksara-senja.svg',
                'gallery_paths'=> null,
                'extra_info'   => null,
                'sale_price'   => null,
                'for_sale'     => false,
            ],

            // ── Data baru: koleksi FOR SALE (harga < 10 juta) ────────
            [
                'title'        => 'Tepi Sawah Subuh',
                'artist'       => 'Kartini Suryani',
                'category'     => 'Pemandangan',
                'description'  => 'Lukisan persawahan di pagi buta dengan kabut tipis dan warna hijau segar. Menangkap keheningan subuh di pedesaan Jawa Barat.',
                'year_created' => '2020',
                'media'        => 'Cat minyak di kanvas',
                'dimensions'   => '60 × 80 cm',
                'daily_rate'   => 0,
                'available'    => true,
                'image_path'   => 'tepi-sawah-subuh.svg',
                'gallery_paths'=> null,
                'extra_info'   => 'Koleksi ini tersedia untuk dibeli.',
                'sale_price'   => 4_500_000,
                'for_sale'     => true,
            ],
            [
                'title'        => 'Pasar Pagi Ciganea',
                'artist'       => 'Dewi Kartika Sari',
                'category'     => 'Figuratif',
                'description'  => 'Kehidupan pasar tradisional pagi hari dengan warna-warna cerah dan penuh semangat. Menggambarkan interaksi pedagang dan pembeli.',
                'year_created' => '2021',
                'media'        => 'Cat air di kertas',
                'dimensions'   => '40 × 60 cm',
                'daily_rate'   => 0,
                'available'    => true,
                'image_path'   => 'pasar-pagi-ciganea.svg',
                'gallery_paths'=> null,
                'extra_info'   => 'Koleksi ini tersedia untuk dibeli.',
                'sale_price'   => 2_800_000,
                'for_sale'     => true,
            ],
            [
                'title'        => 'Anak-anak Waduk Jatiluhur',
                'artist'       => 'Hendra Gunawan Jr.',
                'category'     => 'Figuratif',
                'description'  => 'Potret ceria anak-anak bermain di tepi Waduk Jatiluhur. Warna-warna hangat mencerminkan kegembiraan masa kecil.',
                'year_created' => '2019',
                'media'        => 'Akrilik di kanvas',
                'dimensions'   => '50 × 70 cm',
                'daily_rate'   => 0,
                'available'    => true,
                'image_path'   => 'anak-anak-jatiluhur.svg',
                'gallery_paths'=> null,
                'extra_info'   => 'Koleksi ini tersedia untuk dibeli.',
                'sale_price'   => 3_200_000,
                'for_sale'     => true,
            ],
            [
                'title'        => 'Bukit Santiong Sore Hari',
                'artist'       => 'Ridwan Kamali',
                'category'     => 'Pemandangan',
                'description'  => 'Panorama Bukit Santiong Purwakarta di kala sore dengan langit jingga dan siluet pepohonan.',
                'year_created' => '2022',
                'media'        => 'Cat minyak di kanvas',
                'dimensions'   => '70 × 90 cm',
                'daily_rate'   => 0,
                'available'    => true,
                'image_path'   => 'bukit-santiong.svg',
                'gallery_paths'=> null,
                'extra_info'   => 'Koleksi ini tersedia untuk dibeli.',
                'sale_price'   => 6_750_000,
                'for_sale'     => true,
            ],
            [
                'title'        => 'Gerabah Plered',
                'artist'       => 'Siti Rahayu',
                'category'     => 'Still Life',
                'description'  => 'Komposisi gerabah khas Plered Purwakarta dengan latar kain tradisional. Merayakan kekayaan kerajinan lokal.',
                'year_created' => '2023',
                'media'        => 'Cat minyak di kanvas',
                'dimensions'   => '45 × 55 cm',
                'daily_rate'   => 0,
                'available'    => true,
                'image_path'   => 'gerabah-plered.svg',
                'gallery_paths'=> null,
                'extra_info'   => 'Koleksi ini tersedia untuk dibeli.',
                'sale_price'   => 1_950_000,
                'for_sale'     => true,
            ],
            [
                'title'        => 'Kabut Gunung Burangrang',
                'artist'       => 'Ahmad Fauzi',
                'category'     => 'Pemandangan',
                'description'  => 'Gunung Burangrang diselimuti kabut pagi dengan gradasi ungu dan abu-abu yang memukau.',
                'year_created' => '2021',
                'media'        => 'Akrilik di kanvas',
                'dimensions'   => '80 × 100 cm',
                'daily_rate'   => 0,
                'available'    => true,
                'image_path'   => 'kabut-burangrang.svg',
                'gallery_paths'=> null,
                'extra_info'   => 'Koleksi ini tersedia untuk dibeli.',
                'sale_price'   => 7_500_000,
                'for_sale'     => true,
            ],
            [
                'title'        => 'Tari Jaipong',
                'artist'       => 'Leni Marlina',
                'category'     => 'Figuratif',
                'description'  => 'Gerak dinamis tari Jaipong dalam sapuan warna cerah yang ekspresif. Merekam semangat budaya Sunda.',
                'year_created' => '2020',
                'media'        => 'Cat air di kanvas',
                'dimensions'   => '55 × 75 cm',
                'daily_rate'   => 0,
                'available'    => true,
                'image_path'   => 'tari-jaipong.svg',
                'gallery_paths'=> null,
                'extra_info'   => 'Koleksi ini tersedia untuk dibeli.',
                'sale_price'   => 5_100_000,
                'for_sale'     => true,
            ],
            [
                'title'        => 'Warung Kopi Tepi Rel',
                'artist'       => 'Budi Setiawan',
                'category'     => 'Urban',
                'description'  => 'Suasana warung kopi sederhana di tepi rel kereta dengan nuansa nostalgia dan kehangatan.',
                'year_created' => '2018',
                'media'        => 'Mixed media di kanvas',
                'dimensions'   => '65 × 85 cm',
                'daily_rate'   => 0,
                'available'    => true,
                'image_path'   => 'warung-kopi-rel.svg',
                'gallery_paths'=> null,
                'extra_info'   => 'Koleksi ini tersedia untuk dibeli.',
                'sale_price'   => 3_750_000,
                'for_sale'     => true,
            ],
        ];

        foreach ($rows as $data) {
            Painting::updateOrCreate(
                ['title' => $data['title']],
                array_merge($data, [
                    'slug'       => Str::slug($data['title']) . '-temp',
                    'koleksi_id' => null,
                ])
            );
        }

        foreach (Painting::query()->orderBy('id')->get() as $painting) {
            $painting->forceFill([
                'slug' => Str::slug($painting->title) . '-' . $painting->id,
            ])->saveQuietly();
        }
    }
}